import { z } from "zod";
import type * as Sdk from "@anthropic-ai/claude-agent-sdk" with { "resolution-mode": "import" };
import { PUBLIC_SOURCE_CAP, PUBLIC_SOURCE_URL_MAX_LENGTH, RECORD_REF_ALPHABET, RECORD_REF_MAX_LENGTH, type LearningRecordResult as LearningResult, type LearningToolKind } from "./learning-recording";

export const LEARNING_TOOL_NAME = "mcp__laisora_learning__observe";
export const LEARNING_TOOL_NAMES = [LEARNING_TOOL_NAME, "mcp__laisora_learning__propose", "mcp__laisora_learning__public"];
const TOOL_USE_META_KEY = "claudecode/toolUseId";
const CALLER_UNVERIFIED: LearningResult = { ok: false, code: "caller-unverified", requirement: "R-LRN-12" };
const ROOT_MARK_TTL_MS = 5 * 60_000;
const ROOT_MARK_HOLD_MS = 30 * 60_000;
const ROOT_MARK_CAP = 32;

export const LEARNING_INSTRUCTION = [
  "LAISORA's learning ledger holds usage knowledge valid only for a named model; it expires when that model's name changes. LAISORA delivers it in Model usage knowledge.",
  "Use mcp__laisora_learning__observe after seeing a delegation target behave in this session. Record one line: condition -> observed behavior -> limitation, within 300 code points. Executor, model, effort and role are separate fields.",
  "Do not record universal rankings, task instructions, session-only instructions, or claims that normal completion proves quality. Do not overgeneralize one observation.",
  "LAISORA attaches this conversation's completed delegation runs as evidence; do not supply run IDs. Recording the same line without new delegations does not renew its freshness.",
  "Use mcp__laisora_learning__propose for orchestration practices that hold regardless of model. These proposals are kept for the developer and never delivered.",
  "Use mcp__laisora_learning__public only in a Host-authorized research conversation: submit the whole verified set, one claim per line, with sources and checkedAt; put numbers and their conditions in figures.",
  "[rule] lines are generated by LAISORA from failures that recurred under the named conductor or target model. They state the failure, not a fix. [provisional] observations are unverified. [measured] lines do not measure answer quality.",
  "Project notices mean a failed call had a working-folder path in its arguments and was excluded from general learning. Put permanent project controls in the project's .claude/rules and facts in Claude Code auto memory; do not record them in the ledger.",
  "Follow the always-on placement rule. Never ask the user where to place knowledge. If a write is not authorized, suggest the appropriate destination without writing.",
  "Only the root conversation may record; never ask a subagent to record. Reuse requestId only to retry identical input. Exclude private text, paths, credentials and private URLs from every field.",
].join("\n");

export function learningToolReply(result: LearningResult) {
  return { ...(!result.ok ? { isError: true } : {}), content: [{ type: "text" as const, text: JSON.stringify(result) }] };
}

export class LearningRootGate {
  private readonly marks = new Map<string, number>();

  constructor(private readonly now: () => number = Date.now) {}

  readonly hook: Sdk.HookCallback = async (input) => {
    const value = input as unknown as Record<string, unknown>;
    if (!LEARNING_TOOL_NAMES.includes(String(value.tool_name))) return {};
    if (value.hook_event_name !== "PreToolUse") { this.revoke(value.tool_use_id); return {}; }
    if (value.agent_id !== undefined) {
      return { hookSpecificOutput: { hookEventName: "PreToolUse" as const, permissionDecision: "deny" as const,
        permissionDecisionReason: JSON.stringify(CALLER_UNVERIFIED) } };
    }
    if (typeof value.tool_use_id === "string" && value.tool_use_id) this.mark(value.tool_use_id);
    return {};
  };

  private mark(id: string): void {
    for (const [key, expiry] of this.marks) if (expiry <= this.now()) this.marks.delete(key);
    this.marks.delete(id);
    this.marks.set(id, this.now() + ROOT_MARK_TTL_MS);
    for (const key of this.marks.keys()) {
      if (this.marks.size <= ROOT_MARK_CAP) break;
      this.marks.delete(key);
    }
  }

  private live(id: string): boolean {
    const expiry = this.marks.get(id);
    if (expiry !== undefined && expiry > this.now()) return true;
    this.marks.delete(id);
    return false;
  }

  hold(id: unknown): void { if (typeof id === "string" && this.live(id)) this.marks.set(id, this.now() + ROOT_MARK_HOLD_MS); }
  release(id: unknown): void { if (typeof id === "string" && this.live(id)) this.marks.set(id, this.now() + ROOT_MARK_TTL_MS); }
  revoke(id: unknown): void { if (typeof id === "string") this.marks.delete(id); }
  clear(): void { this.marks.clear(); }

  consume(extra: unknown): boolean {
    const meta = extra && typeof extra === "object" ? (extra as { _meta?: unknown })._meta : undefined;
    const id = meta && typeof meta === "object" ? (meta as Record<string, unknown>)[TOOL_USE_META_KEY] : undefined;
    if (typeof id !== "string" || !this.live(id)) return false;
    this.marks.delete(id);
    return true;
  }
}

const requestId = z.string().describe(`Opaque request ID: 1-${RECORD_REF_MAX_LENGTH} characters from ${RECORD_REF_ALPHABET}; reuse only for identical input.`);
const target = {
  executor: z.enum(["claude", "codex", "agy"]),
  model: z.string().describe("Concrete model UI name from the Host's successful CLI list; no aliases."),
  effort: z.string().describe("An executor effort, or none for a model without effort; public also accepts any."),
  role: z.string().describe("general or a configured roster role; no child or unknown roles."),
  text: z.string().describe("One line within 300 Unicode code points, without URLs. observe: condition -> observed behavior -> limitation. public: one claim without numbers; URLs belong in sources."),
};
export const LEARNING_INPUTS = {
  observe: z.looseObject({ requestId, ...target }),
  propose: z.looseObject({ requestId, text: z.string().describe("One model-independent orchestration practice, one line within 500 code points. Never delivered.") }),
  public: z.looseObject({ requestId, research: z.string().describe("Host-issued research ID from this research conversation."),
    claims: z.array(z.looseObject({ ...target,
      sources: z.array(z.looseObject({ url: z.string().describe(`Public HTTPS URL within ${PUBLIC_SOURCE_URL_MAX_LENGTH} characters, without query, fragment, credentials or private identifiers.`),
        checkedAt: z.string().describe("Check time in UTC: YYYY-MM-DDTHH:mm:ss.sssZ.") })).min(1).max(PUBLIC_SOURCE_CAP),
      figures: z.string().optional().describe("Numbers with benchmark name, version, effort and conditions; one line within 300 code points; never delivered in the normal section."),
    })).min(1) }),
};

export function createLearningMcpServer(sdk: Pick<typeof Sdk, "createSdkMcpServer" | "tool">, gate: LearningRootGate,
  record: (input: unknown, rootVerified: boolean, kind: LearningToolKind) => Promise<LearningResult>) {
  return sdk.createSdkMcpServer({ name: "laisora_learning", tools: (Object.keys(LEARNING_INPUTS) as LearningToolKind[]).map(kind => sdk.tool(kind,
    kind === "observe" ? "Record a model-specific observation: condition -> observed behavior -> limitation. Host attaches completed runs. Only the verified root may record."
      : kind === "propose" ? "Record a model-independent orchestration practice for the developer. Never delivered. Only the verified root may record."
        : "Record the whole validated public research set authorized by the Host. One claim per line; sources and checkedAt required; numbers only in figures. Only the verified root may record.",
    LEARNING_INPUTS[kind] as unknown as Record<string, z.ZodType>,
    async (input, extra) => learningToolReply(await record(input, gate.consume(extra), kind)))) });
}
