import { privateTextR06, textHash } from "./learning";
import { deliverySetHash, type ClaimItem, type DeliveryItem, type ProjectNotice, type RuleState } from "./learning-episodes";
import { failureLabelText } from "./learning-signature";

export const SECTION_HEADING = "Model usage knowledge (from LAISORA's learning ledger; valid only for the named model):";
export const SECTION_LABELS = "Labels: [rule] a failure that recurred under the named conductor or target model, generated by LAISORA; [public] from public sources; [provisional] a conductor observation, not verified; [measured] LAISORA's delegation records, answer quality not measured.";
export const OBSERVATION_CAP_TOTAL = 4;
export const OBSERVATION_CAP_PER_TARGET_TASK = 1;
export const SECTION_CHAR_BUDGET = 6000;
export const PROJECT_NOTICE_CAP = 3;
export const NEW_ITEM_GRACE_DELIVERIES = 3;
export const MEASURED_WINDOW_DAYS = 30;
export const MEASURED_SPARSE_RUNS = 10;
const DAY_MS = 86_400_000;

export interface MeasuredRun {
  readonly runId: string;
  readonly executor: string;
  readonly model: string;
  readonly actualModel?: string;
  readonly actualEffort?: string;
  readonly effort: string;
  readonly role: string;
  readonly outcome: string;
  readonly endAt: string;
  readonly durationMs?: number;
  readonly session?: string;
}

export interface SectionTarget {
  readonly executor: string;
  readonly model: string;
}

export interface MeasuredLine {
  readonly target: SectionTarget;
  readonly full: string;
  readonly compact: string;
}

const targetId = (target: SectionTarget): string => `${target.executor}/${target.model}`;
const codePoints = (text: string): number => [...text].length;

function formatDuration(ms: number): string {
  return ms < 60_000 ? `${Math.max(1, Math.round(ms / 1000))}s` : `${Math.round(ms / 60_000)}m`;
}

function median(values: readonly number[]): number {
  const sorted = [...values].sort((a, b) => a - b);
  const mid = Math.floor(sorted.length / 2);
  return sorted.length % 2 ? sorted[mid] : (sorted[mid - 1] + sorted[mid]) / 2;
}

function outcomeSummary(runs: readonly MeasuredRun[]): string {
  const counts = new Map<string, number>();
  for (const run of runs) counts.set(run.outcome, (counts.get(run.outcome) ?? 0) + 1);
  return [...counts].sort((a, b) => b[1] - a[1] || (a[0] < b[0] ? -1 : 1)).map(([outcome, count]) => `${count} ${outcome}`).join(", ");
}

function groupLine(label: string, runs: readonly MeasuredRun[]): string {
  const known = runs.filter((run) => run.actualModel !== undefined && run.actualModel !== "unknown" && run.actualEffort !== undefined && run.actualEffort !== "unknown");
  const matched = known.filter((run) => run.actualModel === run.model);
  const mismatched = known.filter((run) => run.actualModel !== run.model);
  const ranAs = [...new Set(mismatched.map((run) => run.actualModel as string))].sort()
    .map((model) => `${mismatched.filter((run) => run.actualModel === model).length} ran as ${model}`);
  const suffix = [...ranAs, ...(runs.length > known.length ? [`${runs.length - known.length} unknown`] : [])].map(part => `; ${part}`).join("");
  if (matched.length < MEASURED_SPARSE_RUNS) return `${label}: ${matched.length} ${matched.length === 1 ? "run" : "runs"} (sparse)${suffix}`;
  const sessions = new Set(matched.map((run) => run.session ?? run.runId)).size;
  const normal = matched.filter((run) => run.outcome === "normal" && run.durationMs !== undefined).map((run) => run.durationMs as number);
  const med = normal.length ? `, median ${formatDuration(median(normal))}` : "";
  return `${label}: ${matched.length} runs in ${sessions} sessions, ${outcomeSummary(matched)}${med}${suffix}`;
}

export function measuredLines(runs: readonly MeasuredRun[], targets: readonly SectionTarget[], now: string): MeasuredLine[] {
  const since = Date.parse(now) - MEASURED_WINDOW_DAYS * DAY_MS;
  const recent = runs.filter((run) => Date.parse(run.endAt) <= Date.parse(now) && Date.parse(run.endAt) >= since);
  const lines: MeasuredLine[] = [];
  for (const target of targets) {
    const own = recent.filter((run) => run.executor === target.executor && run.model === target.model);
    if (!own.length) continue;
    const groups = new Map<string, MeasuredRun[]>();
    for (const run of own) {
      const label = `${run.role} ${run.actualEffort ?? "unknown"}`;
      const list = groups.get(label);
      if (list) list.push(run); else groups.set(label, [run]);
    }
    const parts = [...groups.keys()].sort().map((label) => groupLine(label, groups.get(label) as MeasuredRun[]));
    lines.push({ target, full: `- [measured ${MEASURED_WINDOW_DAYS}d] ${parts.join("; ")}`, compact: `- [measured ${MEASURED_WINDOW_DAYS}d] ${groupLine("all", own)}` });
  }
  return lines;
}

export function ruleLine(rule: RuleState): string {
  const scope = rule.key.bind === "target" ? `${rule.key.role} ${rule.key.effort}: ` : "";
  const head = rule.head ? ` \`${rule.head}\`` : "";
  const label = failureLabelText(rule.cls, rule.label) ?? (rule.labelFacts?.code
    ? `${rule.labelFacts.code}${rule.labelFacts.fields?.length ? `; schema fields: ${rule.labelFacts.fields.join(", ")}` : ""}` : undefined);
  const shown = rule.ineffective ? `, ${rule.ineffective} after being shown` : "";
  return `- [rule] ${scope}${rule.tool}${head} → ${rule.cls}${label ? `: ${label}` : ""} (${rule.count} times${shown})`;
}

export function claimLine(claim: ClaimItem): string {
  const tag = claim.source === "public" ? "[public]" : claim.corroborated ? "[provisional]" : "[provisional, uncorroborated]";
  return `- ${tag} ${claim.role} ${claim.effort}: ${claim.text}`;
}

export function noticeLine(notice: ProjectNotice): string {
  const head = notice.head ? ` \`${notice.head}\`` : "";
  return `- ${notice.tool}${head} → ${notice.cls} recurred ${notice.count} times with a working-folder path in the call arguments and was excluded from general learning; write a control to this project's .claude/rules or a fact to auto memory.`;
}

export interface SectionInput {
  readonly conductorModel: string;
  readonly targets: readonly SectionTarget[];
  readonly rules: readonly RuleState[];
  readonly claims: readonly ClaimItem[];
  readonly measured: readonly MeasuredLine[];
  readonly notices: readonly ProjectNotice[];
  readonly currentProject: string;
  readonly deliveredConversations: ReadonlyMap<string, number>;
  readonly usedConversations: ReadonlyMap<string, number>;
  readonly roles?: ReadonlySet<string>;
  readonly arm?: "delivery" | "holdout";
}

export interface SectionResult {
  readonly text: string;
  readonly items: readonly DeliveryItem[];
  readonly setHash: string;
  readonly chars: number;
  readonly dropped: number;
  readonly withheld: readonly { item: DeliveryItem; reason: string }[];
  readonly common: { readonly items: readonly DeliveryItem[]; readonly hash: string; readonly chars: number; readonly compressed?: readonly DeliveryItem[] };
}

interface Knowledge {
  readonly id: string;
  readonly type: "rule" | "claim";
  readonly group: string;
  readonly order: number;
  readonly line: string;
  readonly current: boolean;
  readonly grace: boolean;
  readonly used: number;
  readonly at: string;
  readonly observation?: string;
}

function compareKnowledge(a: Knowledge, b: Knowledge): number {
  if (a.current !== b.current) return a.current ? -1 : 1;
  if (a.grace !== b.grace) return a.grace ? -1 : 1;
  if (!a.grace && a.used !== b.used) return b.used - a.used;
  if (a.at !== b.at) return a.at < b.at ? 1 : -1;
  return a.id < b.id ? -1 : a.id > b.id ? 1 : 0;
}

export function buildSection(input: SectionInput): SectionResult {
  const withheld: { item: DeliveryItem; reason: string }[] = [];
  const knowledge: Knowledge[] = [];
  const groupOrder = new Map<string, number>([["conductor", 0], ...input.targets.map((target, index) => [targetId(target), index + 1] as [string, number])]);
  for (const rule of input.rules) {
    const group = rule.key.bind === "conductor" ? "conductor" : targetId(rule.key);
    if (!groupOrder.has(group) || !rule.active || rule.key.bind === "conductor" && rule.key.model !== input.conductorModel) continue;
    knowledge.push({ id: rule.ruleId, type: "rule", group, order: 1, line: ruleLine(rule), current: input.currentProject !== "unknown" && rule.projects.has(input.currentProject),
      grace: (input.deliveredConversations.get(rule.ruleId) ?? 0) < NEW_ITEM_GRACE_DELIVERIES, used: input.usedConversations.get(rule.ruleId) ?? 0, at: rule.lastAt });
  }
  for (const claim of input.claims) {
    const group = targetId(claim);
    if (privateTextR06(claim.text) || !groupOrder.has(group) || claim.role === "unknown" || claim.role === "child" || /[:/]/.test(claim.role)
      || claim.role !== "general" && !(input.roles ?? new Set(["worker", "explorer", "reviewer"])).has(claim.role)) continue;
    knowledge.push({ id: claim.itemId, type: "claim", group, order: claim.source === "public" ? 2 : 3, line: claimLine(claim),
      current: input.currentProject !== "unknown" && claim.source === "observation" && claim.projects.has(input.currentProject),
      grace: (input.deliveredConversations.get(claim.itemId) ?? 0) < NEW_ITEM_GRACE_DELIVERIES, used: input.usedConversations.get(claim.itemId) ?? 0,
      at: claim.freshAt, ...(claim.source === "observation" ? { observation: group + "\u0000" + claim.role } : {}) });
  }
  knowledge.sort(compareKnowledge);
  const selected = knowledge.filter(item => item.order === 2);
  const measured = new Map(input.measured.map(line => [targetId(line.target), line]));
  let compactMeasured = false;
  let measuredKept = input.targets.filter(target => measured.has(targetId(target))).map(targetId);
  let notices = input.notices.slice(0, PROJECT_NOTICE_CAP);
  for (const notice of input.notices.slice(PROJECT_NOTICE_CAP)) withheld.push({ item: { type: "notice", id: notice.id }, reason: "notice-cap" });
  const dropItem = (item: Knowledge, reason: string): void => {
    selected.splice(selected.indexOf(item), 1);
    withheld.push({ item: { type: item.type, id: item.id }, reason });
  };
  const render = (): string => {
    if (!selected.length && !measuredKept.length && !notices.length) return "";
    const lines = [SECTION_HEADING, SECTION_LABELS];
    for (const [group] of [...groupOrder].sort((a, b) => a[1] - b[1])) {
      const measuredLine = measuredKept.includes(group) ? measured.get(group) : undefined;
      const items = selected.filter(item => item.group === group).sort((a, b) => a.order - b.order || compareKnowledge(a, b));
      if (!measuredLine && !items.length) continue;
      lines.push(group === "conductor" ? "Conductor " + input.conductorModel + ":" : group + ":");
      if (measuredLine) lines.push(compactMeasured ? measuredLine.compact : measuredLine.full);
      lines.push(...items.map(item => item.line));
    }
    if (notices.length) lines.push("Project notices:", ...notices.map(noticeLine));
    return lines.join("\n");
  };
  const itemRefs = (): DeliveryItem[] => [
    ...selected.map(item => ({ type: item.type, id: item.id })),
    ...measuredKept.map(id => ({ type: "measured" as const, id: textHash(`measured:${id}`) })),
    ...notices.map(notice => ({ type: "notice" as const, id: notice.id })),
  ];
  while (codePoints(render()) > SECTION_CHAR_BUDGET) {
    const drop = selected[selected.length - 1];
    if (drop) dropItem(drop, "section-budget");
    else if (!compactMeasured && measuredKept.length) compactMeasured = true;
    else if (measuredKept.length) withheld.push({ item: { type: "measured", id: textHash(`measured:${measuredKept.pop()!}`) }, reason: "section-budget" });
    else if (notices.length) withheld.push({ item: { type: "notice", id: notices.pop()!.id }, reason: "section-budget" });
    else break;
  }
  const commonText = render();
  const common = { items: itemRefs(), hash: textHash(commonText), chars: codePoints(commonText),
    ...(compactMeasured ? { compressed: measuredKept.map(id => ({ type: "measured" as const, id: textHash(`measured:${id}`) })) } : {}) };
  const experimental: Knowledge[] = [];
  const perTask = new Set<string>();
  let observations = 0;
  for (const item of knowledge.filter(item => item.order !== 2)) {
    if (item.observation !== undefined) {
      if (observations >= OBSERVATION_CAP_TOTAL || perTask.has(item.observation)) {
        withheld.push({ item: { type: item.type, id: item.id }, reason: "observation-cap" }); continue;
      }
      observations++; perTask.add(item.observation);
    }
    experimental.push(item); selected.push(item);
  }
  while (codePoints(render()) > SECTION_CHAR_BUDGET && experimental.length) {
    const drop = experimental.filter(item => !item.grace).pop()
      ?? [...experimental].sort((a, b) => a.current !== b.current ? (a.current ? 1 : -1) : a.at < b.at ? -1 : a.at > b.at ? 1 : a.id.localeCompare(b.id))[0];
    experimental.splice(experimental.indexOf(drop), 1); dropItem(drop, "section-budget");
  }
  if (input.arm === "holdout") for (const item of experimental) dropItem(item, "holdout");
  const text = render(), items = itemRefs();
  return { text, items, setHash: deliverySetHash(items), chars: codePoints(text), dropped: withheld.filter(item => item.reason !== "holdout").length, withheld, common };
}
